name: Buildozer APK Derleyici

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Java Kur
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Android SDK Kur
      uses: android-actions/setup-android@v3

    - name: Bağımlılıkları Yükle
      run: |
        sudo apt-get update
        sudo apt-get install -y \
        git zip unzip autoconf libtool pkg-config \
        zlib1g-dev libncurses5-dev libncursesw5-dev \
        cmake libffi-dev libssl-dev build-essential \
        ccache libltdl-dev

    - name: Android Lisanslarını Kabul Et
      run: |
        yes | sdkmanager --licenses

    - name: Build Tools Kur
      run: |
        sdkmanager "platform-tools"
        sdkmanager "platforms;android-33"
        sdkmanager "build-tools;33.0.2"

    - name: Buildozer Kur
      run: |
        python -m pip install --upgrade pip
        pip install --user cython virtualenv
        pip install --user buildozer

    - name: Buildozer Versiyon
      run: |
        ~/.local/bin/buildozer --version

    - name: APK Derle
      run: |
        ~/.local/bin/buildozer android debug

    - name: APK Yükle
      uses: actions/upload-artifact@v4
      with:
        name: BalikBotu-APK
        path: bin/*.apk
