name: Buildozer APK Derleyici

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Python Kurulumu
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Bağımlılıkları Yükle
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: Android SDK ve NDK Önbelleğe Al
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

    - name: APK Derleme İşlemini Başlat
      run: |
        buildozer android debug

    - name: APK Dosyasını İndirme Linki Yap
      uses: actions/upload-artifact@v4
      with:
        name: Metin2-Balik-Botu-APK
        path: bin/*.apk
        
