name: Buildozer APK Derleyici

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodu Klonla
      uses: actions/checkout@v4

    - name: Bağımlılıkları Yükle
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev
        pip install --upgrade pip
        pip install buildozer cython

    - name: APK Derleme
      run: buildozer android debug

    - name: APK Dosyasını İndirme Linki Yap
      uses: actions/upload-artifact@v4
      with:
        name: Metin2-Balik-Botu-APK
        path: bin/*.apk
